# Generated by Django 2.2.14 on 2020-07-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Pain Killers', 'Pain Killers'), ('Syrup', 'Syrup'), ('Tablets', 'Tablets'), ('Injection', 'Injection')], max_length=50, null=True),
        ),
    ]
