# Generated by Django 2.2.14 on 2020-07-24 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storemanager', '0004_auto_20200721_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
